simple_metatag.settings:
  type: config_object
  label: 'Simple Metatag settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable automatic metatag generation'

simple_metatag.gtag_settings:
  type: config_object
  label: 'Google Tag Settings'
  mapping:
    gtag_codes:
      type: sequence
      label: 'Google Tag Codes'
      sequence:
        type: string
        label: 'Google Tag Code'
